objects/Job_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>Importance__c</fullName>
        <label>Importance</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Desired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Years_of_Experience__c</fullName>
        <label>Years of Experience</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>DEPRECATED Job Qualification</label>
    <nameField>
        <displayFormat>JQN-{0000}</displayFormat>
        <label>Job Qualification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Seeker_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Only fill out if relevant</description>
        <inlineHelpText>Only fill out if relevant</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importance__c</fullName>
        <label>Importance</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Years_of_Experience__c</fullName>
        <label>Years of Experience</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <displayFormat>JSQ-{0000}</displayFormat>
        <label>JS Qual Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JoMatchSearch.cls
public class JoMatchSearch {
    
    public static void getJobMatch(){
        //SELECT Id, Importance__c, Name, Weight__c, Years_of_Experience__c FROM Job_Qualification__c;
        //SELECT Id, Start_Date__c, End_Date__c, Years_of_Experience__c FROM Job_Seeker_Qualification__c;
        list<Job_Qualification__c> jobsQualificationList = [SELECT Id, Importance__c, Name, Weight__c, Years_of_Experience__c FROM Job_Qualification__c];
        list<Job_Seeker_Qualification__c> seekerQualificationList =[SELECT Id, Start_Date__c, End_Date__c, Years_of_Experience__c FROM Job_Seeker_Qualification__c];
        
 		system.debug(jobsQualificationList);
        system.debug(seekerQualificationList);
    }
    
    public static double getExperienceScore(){
       return 0;   
    }
    public static double getCertificationScore(){
      return 0;    
    }
    public static double getSkillsScore(){
      return 0;  
    }
    public static double getOverallScore(double expScore, double certScore, double skillScore){
        
        if(expScore == 0) 
            return 0;
        else{
            return expScore + certScore + skillScore;
        }      
        
    }
    
    JoMatchSearch jobSearch = new JoMatchSearch();   
}