objects/Job_Match__c.object
<CustomObject>
    <description>Matches based on requirements and job seeker criteria</description>
    <fields>
        <fullName>Job_Posting__c</fullName>
        <label>Job Posting</label>
        <referenceTo>Job_Posting__c</referenceTo>
        <relationshipLabel>Job Matches</relationshipLabel>
        <relationshipName>Job_Matches</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <label>Job Seeker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Matches</relationshipLabel>
        <relationshipName>Job_Matches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percent_Match__c</fullName>
        <label>Percent Match</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Upsert_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Upsert Key</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Job Match</label>
    <nameField>
        <displayFormat>Match-{00000}</displayFormat>
        <label>Job Match Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Posting__c.object
<CustomObject>
    <fields>
        <fullName>Closing_Date__c</fullName>
        <label>Closing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Qualifications__c</fullName>
        <description>This is what the company job description says and is not used in matching. An algorithm will create records in the Qualifications data.</description>
        <inlineHelpText>This is what the company job description says and is not used in matching. An algorithm will create records in the Qualifications data.</inlineHelpText>
        <label>Qualifications</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>Job-{00000}</displayFormat>
        <label>Job Posting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Seeker_Qualification__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Only fill out if relevant</description>
        <inlineHelpText>Only fill out if relevant</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Importance__c</fullName>
        <label>Importance</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Posting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Posting</label>
        <referenceTo>Job_Posting__c</referenceTo>
        <relationshipLabel>Qualifications</relationshipLabel>
        <relationshipName>Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Seeker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Qualifications</relationshipLabel>
        <relationshipName>Job_Seeker_Qualifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qualifications__c</fullName>
        <globalPicklist>Qualifications</globalPicklist>
        <label>Qualifications</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Years_of_Experience__c</fullName>
        <label>Years of Experience</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <displayFormat>JSQ-{0000}</displayFormat>
        <label>JS Qual Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JobMatchBatch.cls
public class JobMatchBatch implements Database.Batchable<sObject>{

    //Database.executeBatch(new JobMatchBatch(), 2000);

   public Database.QueryLocator start(Database.BatchableContext BC){
       
      // return Database.getQueryLocator('SELECT Id FROM Job_Posting__c WHERE Id=\'a071a00000LebZ2\'');
      return Database.getQueryLocator('SELECT Id FROM Job_Posting__c WHERE Closing_Date__c >= TODAY OR Closing_Date__c = NULL');
   }

   public void execute(Database.BatchableContext BC, List<Job_Posting__c> scope){

      List<Job_Match__c> jobMatches = new  List<Job_Match__c>();
       
          
     Set<Id> jobPosting = new Set<Id>();
     for(Job_Posting__c s : scope){
        jobPosting.add(s.Id);     	
     }
       List<Job_Seeker_Qualification__c> jobsQualificationList = [SELECT Id, Importance__c, Name, Weight__c, Years_of_Experience__c, Qualifications__c, Job_Posting__c, RecordTypeId                                                         
                                                           FROM Job_Seeker_Qualification__c
                                                           WHERE Job_Posting__c IN:jobPosting AND Qualifications__c != NULL];
       Map<Id, List<Job_Seeker_Qualification__c>> jMap = new Map<Id, List<Job_Seeker_Qualification__c>>();
     
       Set<string> qualifications = new Set<string>();
       for(Job_Seeker_Qualification__c s : jobsQualificationList){
           qualifications.add(s.Qualifications__c);
           if(jMap.containsKey(s.Job_Posting__c)){
               List<Job_Seeker_Qualification__c> tempList = jMap.get(s.Job_Posting__c);
               tempList.add(s);
               jMap.put(s.Job_Posting__c, tempList);
           }else{
               jMap.put(s.Job_Posting__c, new List<Job_Seeker_Qualification__c>{s});
           }
            
       }
       
       list<Job_Seeker_Qualification__c> seekerQualificationList =[SELECT Id, Start_Date__c, End_Date__c, Years_of_Experience__c, Job_Seeker__c, Qualifications__c, RecordTypeId
                                                                   FROM Job_Seeker_Qualification__c
                                                                   WHERE Qualifications__c IN:qualifications AND Job_Seeker__c != NULL];
       Map<Id, List<Job_Seeker_Qualification__c>> jsMap = new Map<Id, List<Job_Seeker_Qualification__c>>();
         
       for(Job_Seeker_Qualification__c s : seekerQualificationList){
          
           if(jsMap.containsKey(s.Job_Seeker__c)){
               List<Job_Seeker_Qualification__c> tempList = jsMap.get(s.Job_Seeker__c);
               tempList.add(s);
               jsMap.put(s.Job_Seeker__c, tempList);
           }else{
               jsMap.put(s.Job_Seeker__c, new List<Job_Seeker_Qualification__c>{s});
           }
            
       }
       
       for(Id jpId:jMap.keySet()){
           List<Job_Seeker_Qualification__c> jqlist = jMap.get(jpId);
           for(Id jsId:jsMap.keySet()){
               List<Job_Seeker_Qualification__c> jslist = jsMap.get(jsId);              
               integer totalQualifications =  jqlist.size();
              /* integer matchQualifications = getCompare(jqlist, jslist);
               integer result = totalQualifications - matchQualifications;
               double matchScore = (1- (result/totalQualifications))*100;
               
               system.debug('Total, Match, Result, Score' + totalQualifications + ',' + matchQualifications + ',' + result + ',' + matchScore);*/
               double matchScore = getCompare(jqlist, jslist);
               if(matchScore > 0)
               	jobMatches.add(new Job_Match__c(Job_Seeker__c = jsId, Job_Posting__c = jpId, Percent_Match__c = matchScore, Upsert_Key__c= jpId + '|' + jsId));
           }
       }
      system.debug(jobMatches);
	  UPSERT jobMatches Upsert_Key__c;       
      
    }
    
    public static double getCompare(List<Job_Seeker_Qualification__c> jqlist, List<Job_Seeker_Qualification__c> jslist){
        integer matchesFound = 0;
        double percentageScore= 0.0;
        List<Job_Seeker_Qualification__c> jobRequire = new List<Job_Seeker_Qualification__c>();
        for(Job_Seeker_Qualification__c jq:jqlist){
            if (jq.Importance__c == 'Required'){
                jobRequire.add(jq);
            }
        }
        
        integer numberRequire = jobRequire.size();
        integer seekerReq = 0;
        for(Job_Seeker_Qualification__c jq:jobRequire){
            for(Job_Seeker_Qualification__c js:jslist){
                if(jq.Qualifications__c == js.Qualifications__c){
                    seekerReq++;
                }
            }
        }
        
        if(seekerReq < numberRequire)
            return 0;
         double totalMatch = 0.0;
        for(Job_Seeker_Qualification__c jq:jqlist){
            double yearJob = jq.Years_of_Experience__c;          
            if(yearJob == null)
                yearJob = 0.0; 
            if(yearJob > 10)
                yearJob=10;
            double weightJob = jq.Weight__c;
            if(weightJob == null)
                weightJob = 5.0;
            weightJob = (10 -weightJob)*10;
            for(Job_Seeker_Qualification__c js:jslist){
                double seekYear = js.Years_of_Experience__c;
                if(seekYear == null)
                    seekYear = 0.0;  
                 if(seekYear > 10)
                	seekYear=10;
                if(jq.Qualifications__c == js.Qualifications__c){ 
                    if(yearJob != 0){
                        double tempExp = (((seekYear/yearJob)*100)+weightJob)/2 ;             
                    	totalMatch += tempExp;
                    }                     
                   
                    // double tempExp =-1*(Math.log(Math.abs(yearJob - seekYear))) + 0.01;
                    // double tempExp =Math.log(Math.abs(yearJob - seekYear)) + 0.01;                         
                    // weightExp.add(new Map<string, double>{'weight'=>weightJob, 'exp'=>tempExp });          
                }               
            }
        }
        
        if(jqlist.size() == 0)
            return 0;
        
        percentageScore = totalMatch/jqlist.size();
        return percentageScore;
    }
    
    public void finish(Database.BatchableContext BC){
    }
    
}